name: ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'
      - id: cache-dependencies
        name: Cache dependencies
        uses: actions/cache@v2.1.7
        with:
          path: ${{ github.workspace }}/.venv
          key: dependencies-${{ hashFiles('**/poetry.lock') }}
          restore-keys: dependencies-
      - name: Install dependencies
        if: steps.cache-dependencies.cache-hit != 'true'
        run: |
          python -m pip install -U pip poetry
          poetry --version
          poetry env use /usr/bin/python3
          poetry check --no-interaction
          poetry config virtualenvs.in-project true
          poetry install --no-interaction
      - name: Run tests
        run: |
          make test